apiVersion: v1
kind: Namespace
metadata:
  name: openshift-file-integrity
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: policy-fileintegrity-operator
  namespace: openshift-file-integrity
spec:
  pathname: 'https://github.com/ansonmez/rhacmgitopslab.git'
  type: GitHub
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: policy-fileintegrity-operator   
  namespace: openshift-file-integrity 
spec:
  selector:
    matchExpressions:
      - key: 
        operator: In
        values:
        - httpd 
  componentKinds:
  - group: app.ibm.com/v1alpha1
    kind: Subscription
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: policy-fileintegrity-operator  
  name: cluster1only
  namespace: openshift-file-integrity 
spec:
  clusterSelector:
    matchLabels:
      clusterid: cluster1
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: policy-fileintegrity-operator                           
  namespace: openshift-file-integrity
  annotations:
    apps.open-cluster-management.io/github-branch: master
    apps.open-cluster-management.io/github-path: lab-4-assets
spec:
  channel:  openshift-file-integrity
  placement: 
    placementRef: 
      kind: PlacementRule
      name: cluster1only    